server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/decoder-ead/config-server-repo
          default-label: master
          username: rodrigobacchetti
          password:

ead:
  config-server:
    username: "configserver"
    password: "ead123cs"
  service-registry:
    username: "serviceregistry"
    password: "ead123sr"

eureka:
  client:
    service-url:
      defaultZone: "http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka"
  instance:
    hostname: localhost
